# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The analyzer can be invoked from the command line by running
# `flutter analyze`.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # prefer_single_quotes: true
