apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiss-media-player-media
  labels:
    app: kiss-media-player
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
