apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiss-media-player-db
  labels:
    app: kiss-media-player
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
